// SPDX-License-Identifier: MIT
// Copyright 2026 Tom F. <tomf@tomtomtech.net> (https://github.com/tomtom215)

mod amqp;
mod aws_sigv4;
mod bgp;
mod caldav;
mod consul;
mod dns;
mod doh;
pub(crate) mod duckdb_secrets_bridge;
mod elasticsearch;
mod ffi;
mod ftp;
mod ftp_cache;
mod graphql;
mod grpc;
mod grpc_reflect;
mod http;
mod imap;
mod imap_write;
mod influxdb;
mod ipmi;
mod json;
mod jsonrpc;
mod kafka;
mod ldap;
mod ldap_write;
mod mdns;
mod memcached;
mod mqtt;
mod nats;
mod ntp;
mod oauth2;
mod ocsp;
mod metadata;
mod odata;
mod pagination;
mod ping;
mod prometheus;
mod ptp;
mod radius;
mod rate_limit;
mod redis_client;
mod redis_resp;
mod runtime;
mod s3;
mod scp;
pub(crate) mod secrets;
pub(crate) mod secrets_resolve;
pub(crate) mod security;
pub(crate) mod security_validate;
pub(crate) mod security_warnings;
mod sftp;
mod sip;
mod smtp;
mod snmp;
mod soap;
mod ssh;
mod stun;
mod syslog;
mod tls_inspect;
mod vault;
mod webdav;
mod websocket;
mod whois;
mod zeromq;

quack_rs::entry_point_v2!(duck_net_init_c_api, |con| { ffi::register_all(con) });
