// SPDX-License-Identifier: MIT
// Copyright 2026 Tom F. <tomf@tomtomtech.net> (https://github.com/tomtom215)

mod amqp;
mod aws_sigv4;
mod bgp;
mod caldav;
mod consul;
mod dns;
mod doh;
mod elasticsearch;
mod ffi;
mod ftp;
mod ftp_cache;
mod graphql;
mod grpc;
mod http;
mod imap;
mod influxdb;
mod ipmi;
mod json;
mod jsonrpc;
mod kafka;
mod ldap;
mod mdns;
mod memcached;
mod mqtt;
mod nats;
mod ntp;
mod ocsp;
mod odata;
mod pagination;
mod ping;
mod prometheus;
mod ptp;
mod radius;
mod rate_limit;
mod redis_client;
mod runtime;
mod s3;
pub(crate) mod secrets;
pub(crate) mod security;
mod sftp;
mod sip;
mod smtp;
mod snmp;
mod soap;
mod ssh;
mod stun;
mod syslog;
mod tls_inspect;
mod vault;
mod webdav;
mod websocket;
mod whois;
mod zeromq;

quack_rs::entry_point_v2!(duck_net_init_c_api, |con| { ffi::register_all(con) });
